#!/bin/sh
#cd tabula-java
#git submodule init
#git submodule update
#git pull

TARGET="tabula-java"
BACKUP="tabula-java-backup"

function clean_project()
{
    make clean
}

function init_tabula_repo()
{
    git submodule init
}

function update_tabula_repo()
{
    git submodule update
    git pull
}

function go_to_tabula_directory()
{
    cd $TARGET
}

#==============================================================================
# MAIN

if [ -e $TARGET/target ]; then
    clean_project
fi

# go_to_tabula_directory
if [ ! -e $TARGET/src ]; then
    echo "Initing tabula repo: $PWD"
    init_tabula_repo
    update_tabula_repo
else
    echo "Updating tabula repo: $PWD"
    git pull
fi

